---
title: "Practical 0"
author: "Nathan Smith"
date: "13/05/2022"
output: 
  html_document: 
    theme: journal
    fig_width: 5
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(datasauRus)
```

## 1. Datasauraus overview

```{r total_count, echo=FALSE}
?datasaurus_dozen
datasaurus_dozen %>%
  count(dataset)
head(datasaurus_dozen)
```
Datasaurus dozen has 1846 rows and three variables: dataset, x, and y

## 2. Plot of dino 
```{r dino, echo=FALSE}

dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()

dino_data %>%
  summarize(r = cor(x, y))
```  
dino correlation coefficient = -0.0645

## 3. Plot of star
```{r star, echo=FALSE}

star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()


star_data %>%
  summarize(r = cor(x, y))
```  
star correlation coefficient = -0.0630
value is almost identical to dino

## 4. Plot of circle
```{r circle, echo=FALSE}

circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()

circle_data %>%
  summarize(r = cor(x, y))
``` 
star correlation coefficien = -0.068
value is very close to dino and star

## 5. All Plots
```{r All, echo=FALSE}

ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")

datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
```